export const PROJECT_AUTH = Symbol("PREVIEWFORGE_PROJECT_AUTH");
export const PROJECT_INSTALLATION_REPOSITORY = Symbol(
  "PREVIEWFORGE_PROJECT_INSTALLATION_REPOSITORY",
);
export const PROJECT_GITHUB = Symbol("PREVIEWFORGE_PROJECT_GITHUB");
export const PROJECT_REPOSITORY = Symbol("PREVIEWFORGE_PROJECT_REPOSITORY");
export const PROJECT_CREDENTIAL_CIPHER = Symbol("PREVIEWFORGE_PROJECT_CREDENTIAL_CIPHER");
