apiVersion: 1

datasources:
  - name: M8 Prometheus
    uid: m8-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: M8 Tempo
    uid: m8-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
