export const LIVE_OUTPUT_AUTH = Symbol("PREVIEWFORGE_LIVE_OUTPUT_AUTH");
export const LIVE_OUTPUT_DASHBOARD = Symbol("PREVIEWFORGE_LIVE_OUTPUT_DASHBOARD");
export const LIVE_OUTPUT_LOGS = Symbol("PREVIEWFORGE_LIVE_OUTPUT_LOGS");
